### PR TITLE
Moving SGFS, CSG from pymc3 to pymc3-experimental 

### PR DESCRIPTION
**Pull request by vbsinha**
This work is related to ([#3353](https://github.com/pymc-devs/pymc3/issues/3353)). The corresponding PR in pymc3 repo is ([#3391](https://github.com/pymc-devs/pymc3/pull/3391)). Here is the summary of the changes:

1. Moved sgmcmc.py to this repo.
2. Moved the test file: test_sgfs.py to this repo.
3. Moved three notebooks using SGFS and CSG to this repo.

The file test_sgfs can be run by ```python test_sgfs.py```.

@twiecki Could you please review and point out if there are any issues?

### CODE REVIEW

**Comment by junpenglao** [comment]
You should copy the TravisCI setup from PyMC3 to here so that the code will get tested.

**Comment by vbsinha** [comment]
In case we create an independent library as [@twiecki](https://github.com/pymc-devs/pymc3/issues/3353#issuecomment-469018703) has suggested or we need the TravisCI setup as [@junpenglao](https://github.com/pymc-devs/pymc3-experimental/pull/1#issuecomment-469003086) has suggested, we need to create a proper directory structure and write setup.py etc. At the moment I have just placed the newly added python files in the main directory which will have to move when the directory structure is organized. The notebooks do not import SGFS and CSG from the python files instead they do it from original pymc3. This too would need to change. Please guide me how should I continue.

**Comment by twiecki** [comment]
@vbsinha Want to set that up (most can be copied from pymc3)? I can merge this and we can do follow up PRs.

**Comment by vbsinha** [comment]
@twiecki I would like to try setting things up, following the same directory structure as pymc3. Starting a new PR for this might be a good idea.

**Pull request merged**
